Repository dusk-network/kadcast, pull requests merged in 2021-12, with the labels that each got.

#61 Update toolchain and refactor `report` method
  CHANGELOG.md
  Cargo.toml
  rust-toolchain
  src/lib.rs
Labels: team:WebTech

#64 Change `on_message` callback into a trait
  CHANGELOG.md
  examples/main.rs
  src/lib.rs
Labels: team:WebTech

#62 Added auto-propagate flag for broadcast messages
  ARCHITECTURE.md
  CHANGELOG.md
  examples/main.rs
  src/handling.rs
  src/lib.rs
Labels: team:WebTech

#65 Added send method to Peer
  CHANGELOG.md
  src/lib.rs
Labels: team:WebTech

#66 Add metadata to on_message callback
  CHANGELOG.md
  examples/main.rs
  src/handling.rs
  src/lib.rs
Labels: team:WebTech

#70 Add listen_address to override public_address used in header
  CHANGELOG.md
  examples/main.rs
  src/lib.rs
  src/peer.rs
  src/transport.rs
Labels: team:WebTech

#73 Parametrize RaptorQ configuration
  CHANGELOG.md
  Cargo.toml
  HEADER_TEMPLATE
  examples/main.rs
  rustfmt.toml
  src/lib.rs
  src/transport.rs
  src/transport/encoding.rs
  src/transport/encoding/plain_encoder.rs
  src/transport/encoding/raptorq.rs
  src/transport/encoding/raptorq/decoder.rs
  src/transport/encoding/raptorq/encoder.rs
  src/transport/encoding/raptorq_encoder.rs
Labels: area:p2p, team:WebTech, mark:testnet

#75 Allow K_K env! override
  Cargo.toml
  src/kbucket.rs
  src/lib.rs
Labels: mark:testnet

#77 Use channel send
  CHANGELOG.md
  src/encoding.rs
  src/encoding/error.rs
  src/encoding/header.rs
  src/encoding/message.rs
  src/encoding/payload/broadcast.rs
  src/encoding/payload/nodes.rs
  src/handling.rs
  src/kbucket/key.rs
  src/lib.rs
  src/mantainer.rs
  src/transport.rs
  src/transport/encoding/raptorq/encoder.rs
Labels: mark:testnet
