Repository dusk-network/kadcast, pull requests merged in 2022-01, with the labels that each got.

#79 Improve network discovery
  CHANGELOG.md
  src/handling.rs
  src/kbucket.rs
  src/kbucket/bucket.rs
  src/lib.rs
  src/mantainer.rs
  src/transport.rs
  src/transport/encoding/raptorq.rs
  src/transport/encoding/raptorq/encoder.rs
Labels: team:WebTech, mark:testnet

#81 Fix deadlock on RWLock
  CHANGELOG.md
  Cargo.toml
  src/handling.rs
  src/lib.rs
  src/mantainer.rs
  src/transport.rs
Labels: mark:testnet

#84 Add `send interval` and `FEC redundancy` configuration
  CHANGELOG.md
  Cargo.toml
  src/handling.rs
  src/lib.rs
  src/transport.rs
  src/transport/encoding/raptorq/encoder.rs
  src/transport/sockets.rs
Labels: mark:testnet

#85 Add test-harness
  .github/workflows/build.yml
  Cargo.toml
  src/handling.rs
  src/transport.rs
  src/transport/encoding/raptorq/decoder.rs
  src/transport/sockets.rs
  tests/lib.rs
Labels: mark:testnet

#88 Add UDP network configuration
  CHANGELOG.md
  Cargo.toml
  src/handling.rs
  src/transport.rs
  src/transport/encoding/raptorq.rs
  src/transport/encoding/raptorq/encoder.rs
  src/transport/sockets.rs
  tests/lib.rs
Labels: mark:testnet

#89 Handle and try to decode chunks in a separate tokio task
  CHANGELOG.md
  src/lib.rs
  src/transport.rs
Labels: mark:testnet

#95 Kadcast serde Config
  CHANGELOG.md
  Cargo.toml
  examples/main.rs
  src/config.rs
  src/handling.rs
  src/kbucket.rs
  src/kbucket/bucket.rs
  src/lib.rs
  src/peer.rs
  src/transport.rs
  src/transport/encoding.rs
  src/transport/encoding/plain_encoder.rs
  src/transport/encoding/raptorq.rs
  src/transport/encoding/raptorq/decoder.rs
  src/transport/encoding/raptorq/encoder.rs
  src/transport/sockets.rs
  tests/lib.rs
Labels: mark:testnet

#98 Implement a safe bootstrap
  CHANGELOG.md
  Cargo.toml
  src/mantainer.rs
  tests/lib.rs
Labels: fix:bug, mark:testnet

#100 Retry on dns failure
  CHANGELOG.md
  Cargo.toml
  src/mantainer.rs
Labels: fix:bug, mark:testnet

#102 Fix dupemap cache
  CHANGELOG.md
  Cargo.toml
  src/transport/encoding/raptorq/decoder.rs
Labels: mark:testnet
